# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:41
from __future__ import unicode_literals

import concurrency.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=30, verbose_name='Ch\xe4\u0159')),
                ('integer', models.IntegerField()),
                ('positive_integer', models.PositiveIntegerField()),
                ('max_value_10', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('range_5_10', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('boolean', models.BooleanField(default=False)),
                ('choices', models.IntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3')])),
                ('unique', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('small_integer', models.SmallIntegerField(default=1)),
                ('positive_small_integer', models.PositiveSmallIntegerField()),
                ('null_boolean', models.NullBooleanField(default=None)),
                ('date_range', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2000, 12, 31))])),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('time', models.TimeField()),
                ('decimal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('float', models.FloatField()),
                ('big_integer', models.BigIntegerField()),
                ('generic_ip', models.GenericIPAddressField()),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('required', models.CharField(max_length=255)),
                ('nullable', models.CharField(blank=True, max_length=255, null=True)),
                ('blank', models.CharField(blank=True, max_length=255, null=True)),
                ('not_editable', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('version', concurrency.fields.IntegerVersionField(default=1, help_text='record revision number')),
            ],
        ),
        migrations.CreateModel(
            name='DemoModelVBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.IntegerField()),
                ('col2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demomodel',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Option'),
        ),
    ]
